server:
  port: 80
  servlet:
    context-path: /rbac


spring:
  resources:
    static-locations: classpath:/temp/,classpath:/static/,classpath:/lib/
  mvc:
    servlet:
      #一般配置中应该添加前端控制器在服务器时就进行初始化
      load-on-startup: 1
    static-path-pattern: /**
  thymeleaf:
    #前缀，也就是模板存放的路径
    prefix: classpath:/templates/
    #编码格式
    encoding: UTF-8
    #关闭缓存，不然无法看到实时页面
    cache: false
    #后缀
    suffix: .html
    #设置不严格的html
    mode: HTML
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_rbac?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    # 连接池的配置信息:初始化大小，最小，最大
    initial-size: 8
    min-idle: 1
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    #验证库是否正常sql
    validation-query: select 'x' from dual
    #空闲时验证，防止连接断开
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    use-global-data-source-stat: true
  #时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  #Mapper.xml所在的位置
  mapper-locations: classpath*:mapper/*.xml
  #Entity扫描的model包
  type-aliases-package: com.hc.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
  reasonable: true
  params: count=countSql

logging:
  config: classpath:logback-spring.xml

debug: true
